apiVersion: v1
kind: BuildConfig
metadata:
  name: pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      env:
        - name: PROJECTNAME
          description: Name of the project in OpenShift
        - name: DOMAINNAME
          description: The domain name of the OpenShift server
          value: dev2.conygre.com
        - name: GITREPOENV
          description: Git repository URL for the OpenShift templates
          value: https://bitbucket.org/stevshil/nafal.git
        - name: GITREPOAPI
          description: Git repository URL for your API Application layer
          value: https://bitbucket.org/stevshil/tca-docker.git
        - name: GITREPODB
          description: Git repository URL for your Database and Message Queue layer
          value: https://bitbucket.org/stevshil/tca-docker.git
        - name: GITREPOTEST
          description: Git repository URL for your end to end tests
          value: "false"
        - name: APIVERSION
          description: The version number for your API layer container and code
          value: 0.0.1
        - name: DBVERSION
          description: The version number for you Database layer container
          value: 0.0.1
        - name: MQVERSION
          description: The version number for you Message Queue layer container
          value: 0.0.1
        - name: BRANCHENV
          description: The branch name to use for the environment
          value: master
        - name: BRANCHAPI
          description: The branch name to use for the API layer container and code
          value: master
        - name: BRANCHDB
          description: The branch name to use for the Database and Message Queue layer container
          value: master
        - name: BRANCHTEST
          description: The branch name to use for the end to end testing
          value: master
        - name: DOCKERREG
          description: The hostname and port number for your private docker registry
          value: dockerreg.conygre.com:5000
        - name: BUILDDB
          description: Whether you want to include the Database and Message Queue as part of the build (true for the first build)
          value: "false"
        - name: APICHKURL
          description: URL to check to ensure application is ready and running
          value: /api
        - name: APIPORT
          description: Port number container is listening on
          value: 80
        - name: AMQMOUNT0
          description: Persistent data storage directory within the container for Message Queue
          value: /data/activemq
        - name: AMQMOUNT1
          description: Persistent log storage directory within the container for Message Queue
          value: /var/log/activemq
        - name: DBMOUNT
          description: Persistent data storage directory within the database container
          value: /var/lib/mysql
        - name: MYSQLROOTPW
          description: Root password for MySQL
          value: root
        - name: MAVENOPTIONS
          description: Options to supply to mvn to build your project and test
          value: -Dmaven.test.skip=true clean package
      jenkinsfile: |-
        pipeline {
          agent none
          stages {
            stage ("Create OpenShift Environment") {
              agent {label 'maven'}
              when {
                environment name: 'BUILDDB', value: 'true'
              }
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/${BRANCHENV}"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'environment']
                                ],
                                userRemoteConfigs: [[url: "${GITREPOENV}"]]
                            ])
                  }
                }
                stage("Create API image stream") {
                  steps {
                    dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/API/imagestream.yaml)\"\\" | oc apply -f -'
                    }
                  }
                }
                stage("Create or Update API Deployment Config") {
                  steps {
                  dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/API/deploymentConfig.yaml)\"\\" | oc apply -f -'
                    }
                  }
                }
                stage("Create or updated API Service") {
                  steps {
                    dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/API/service.yaml)\"\\" | oc apply -f -'
                    }
                  }
                }
                stage("Create API Public route") {
                  steps {
                    dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/API/routefe.yaml)\"\\" | oc apply -f -'
                      sh 'echo "Internet route is `oc get route | awk \'{print $2}\' | grep ${PROJECTNAME}`"'
                    }
                  }
                }

                stage("Create persistent storage for DB and MQ") {
                  steps {
                    dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/ActiveMQ/persistentVolume-claim0.yaml)\"\\" | oc apply -f -'
                      sh 'eval echo \\""\$(cat openshift-config/ActiveMQ/persistentVolume-claim1.yaml)\"\\" | oc apply -f -'
                      sh 'eval echo \\""\$(cat openshift-config/MySQL/persistentVolume-claim0.yaml)\"\\" | oc apply -f -'
                    }
                  }
                }
                stage("Create Image Stream for DB and AMQ") {
                  steps {
                    dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/ActiveMQ/imagestream.yaml)\"\\" | oc apply -f -'
                      sh 'eval echo \\""\$(cat openshift-config/MySQL/imagestream.yaml)\"\\" | oc apply -f -'
                    }
                  }
                }
                stage("Create DB and MQ Deployment Config") {
                  steps {
                    dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/ActiveMQ/deploymentConfig.yaml)\"\\" | oc apply -f -'
                      sh 'eval echo \\""\$(cat openshift-config/MySQL/deploymentConfig.yaml)\"\\" | oc apply -f -'
                    }
                  }
                }
                stage("Create Services for DB and AMQ") {
                  steps {
                    dir('environment') {
                      sh 'oc apply -f openshift-config/MySQL/service.yaml'
                      sh 'oc apply -f openshift-config/ActiveMQ/service.yaml'
                    }
                  }
                }
              }
            }
            stage("Build API") {
              agent {label 'maven'}
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/${BRANCHAPI}"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'api']
                                ],
                                userRemoteConfigs: [[url: "${GITREPOAPI}"]]
                            ])
                  }
                }
                stage("Build JAR") {
                  steps {
                    dir('api') {
                      sh 'mvn ${MAVENOPTIONS}'
                    }
                  }
                }
                stage("Create Build For Java Spring Boot Server") {
                  steps {
                    dir('api') {
                      sh 'oc new-build --strategy docker --binary --name api --to=${DOCKERREG} --to-docker || echo "Build already exists"'
                      sh "oc patch bc api -p '{\"spec\":{\"output\": {\"to\": {\"kind\": \"DockerImage\", \"name\": \"${DOCKERREG}/${PROJECTNAME}/api:${APIVERSION}\"}} }}'"
                    }
                  }
                }
                stage("Build API Server Image") {
                  steps {
                    dir('api') {
                      sh 'oc start-build api --from-dir . --follow --wait=true || (echo "BUILD FAILED" && exit 1)'
                    }
                  }
                }
              }
            }
            stage("Build Database and Message Queue Servers") {
              agent {label 'maven'}
              when {
                environment name: 'BUILDDB', value: 'true'
              }
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/${BRANCHDB}"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'dbmq']
                                ],
                                userRemoteConfigs: [[url: "${GITREPODB}"]]
                            ])
                  }
                }
                stage("Create Build For Database Server") {
                  steps {
                    dir('dbmq/db') {
                      sh 'oc new-build --strategy docker --binary --name mysql --to=${DOCKERREG} --to-docker || echo "Build already exists"'
                      sh "oc patch bc mysql -p '{\"spec\":{\"output\": {\"to\": {\"kind\": \"DockerImage\", \"name\": \"${DOCKERREG}/${PROJECTNAME}/mysql:${APIVERSION}\"}} }}'"
                    }
                  }
                }
                stage("Build Database Image") {
                  steps {
                    dir('dbmq/db') {
                      sh 'oc start-build mysql --from-dir . --follow --wait=true'
                    }
                  }
                }
                stage("Create Build For Message Queue Server") {
                  steps {
                    dir('dbmq/mq') {
                      sh 'oc new-build --strategy docker --binary --name activemq --to=${DOCKERREG} --to-docker || echo "Build already exists"'
                      sh "oc patch bc activemq -p '{\"spec\":{\"output\": {\"to\": {\"kind\": \"DockerImage\", \"name\": \"${DOCKERREG}/${PROJECTNAME}/activemq:${APIVERSION}\"}} }}'"
                    }
                  }
                }
                stage("Build Message Queue Server Image") {
                  steps {
                    dir('dbmq/mq') {
                      sh 'oc start-build activemq --from-dir . --follow --wait=true'
                    }
                  }
                }
              }
            }
            stage("Test Application") {
              agent {label 'maven'}
              when {
                not { environment name: 'GITREPOTEST', value: 'false' }
              }
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/${BRANCHTEST}"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'tests']
                                ],
                                userRemoteConfigs: [[url: "${GITREPOTEST}"]]
                            ])
                  }
                }
                stage("Test environment") {
                  steps {
                    dir('tests') {
                      sh 'echo "You should perform tests to make sure your application works"'
                      sh 'echo "Something like a curl to a status port -  curl http://trades.dev2.conygre.com/trades/status"'
                      sh 'echo "Or http://trades.dev2.conygre.com/trades/list"'
                    }
                  }
                }
              }
            }
          }
        }
    type: JenkinsPipeline
    triggers: {
      pollSCM('H */2 * * 1-5')
    }
