apiVersion: v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/display-name: api Image Stream
      description: >-
        api server Image Stream.
    from:
      kind: DockerImage
      name: ${DOCKERREG}/${PROJECTNAME}/api:${APIVERSION}
    generation: null
    importPolicy:
      insecure: true
    name: api:${APIVERSION}
status:
  dockerImageRepository: ""
