apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
  - name: "${APIPORT}"
    port: ${APIPORT}
    targetPort: ${APIPORT}
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
