apiVersion: v1
kind: BuildConfig
metadata:
  name: pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      env:
        - name: PROJECTNAME
          description: Name of the project in OpenShift
        - name: DOMAINNAME
          value: dev1.conygre.com
        - name: GITREPOENV
          value: https://bitbucket.org/stevshil/openshift-templates.git
        - name: GITREPOAPI
        - name: GITREPODB
        - name: GITREPOTEST
          value: "false"
        - name: APIVERSION
          value: 0.0.1
        - name: DBVERSION
          value: 0.0.1
        - name: BRANCHENV
          value: master
        - name: BRANCHAPI
          value: master
        - name: BRANCHDB
          value: master
        - name: BRANCHTEST
          value: master
        - name: DOCKERREG
          value: dockerreg.conygre.com:5000
        - name: BUILDDB
          value: "false"
        - name: APICHKURL
          value: /
      jenkinsfile: |-
        pipeline {
          agent none
          stages {
            stage ("Create OpenShift Environment") {
              agent {label 'maven'}
              when {
                environment name: 'BUILDDB', value: "true"
              }
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/${BRANCHENV}"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'environment']
                                ],
                                userRemoteConfigs: [[url: "${GITREPOENV}"]]
                            ])
                  }
                }
                stage("Create API image stream") {
                  steps {
                    dir('environment') {
                      sh 'eval echo \\"\"$(cat openshift-config/API/imagestream.yaml)\"\\" | oc apply -f -'
                    }
                  }
                }
                stage("Create or Update API Deployment Config") {
                  steps {
                  dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/API/deploymentConfig.yaml)\"\\" | oc apply -f -'
                    }
                  }
                }
                stage("Create or updated API Service") {
                  steps {
                    dir('environment') {
                      sh 'oc apply -f openshift-config/API/service.yaml'
                    }
                  }
                }
                stage("Create API Public route") {
                  steps {
                    dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/API/route.yaml)\"\\" | oc apply -f -'
                      sh 'echo "Internet route is `oc get route | awk \'{print $2}\' | grep ${PROJECTNAME}`"'
                    }
                  }
                }

                stage("Create persistent storage for DB") {
                  steps {
                    dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/MySQL/persistentVolume-claim0.yaml)\"\\" | oc apply -f -'
                    }
                  }
                }
                stage("Create Image Stream for DB") {
                  steps {
                    dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/MySQL/imagestream.yaml)\"\\" | oc apply -f -'
                    }
                  }
                }
                stage("Create DB Deployment Config") {
                  steps {
                    dir('environment') {
                      sh 'eval echo \\""\$(cat openshift-config/MySQL/deploymentConfig.yaml)\"\\" | oc apply -f -'
                    }
                  }
                }
                stage("Create Services for DB") {
                  steps {
                    dir('environment') {
                      sh 'oc apply -f openshift-config/MySQL/service.yaml'
                    }
                  }
                }
              }
            }
            stage("Build API") {
              agent {label 'maven'}
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/${BRANCHAPI}"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'api']
                                ],
                                userRemoteConfigs: [[url: "${GITREPOAPI}"]]
                            ])
                  }
                }
                stage("Build JAR") {
                  steps {
                    dir('api') {
                      sh 'mvn -Dmaven.test.skip=true clean package'
                    }
                  }
                }
                stage("Create Build For Java Spring Boot Server") {
                  steps {
                    dir('api') {
                      sh 'oc new-build --strategy docker --binary --name api --to=${DOCKERREG} --to-docker || echo "Build already exists"'
                    }
                  }
                }
                stage("Build api Server Image") {
                  steps {
                    dir('api') {
                      sh 'oc start-build api --from-dir . --follow --wait=true || (echo "BUILD FAILED" && exit 1)'
                      sh "oc tag ${PROJECTNAME}/api:latest ${PROJECTNAME}/api:${APIVERSION}"
                    }
                  }
                }
              }
            }
            stage("Build Database Server") {
              agent {label 'maven'}
              when {
                environment name: 'BUILDDB', value: "true"
              }
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/${BRANCHDB}"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'db']
                                ],
                                userRemoteConfigs: [[url: "${GITREPODB}"]]
                            ])
                  }
                }
                stage("Create Build For Database Server") {
                  steps {
                    dir('db') {
                      sh 'oc new-build --strategy docker --binary --name mysql --to=${DOCKERREG} --to-docker || echo "Build already exists"'
                    }
                  }
                }
                stage("Build Database Image") {
                  steps {
                    dir('db') {
                      sh 'oc start-build mysql --from-dir . --follow --wait=true && rm Dockerfile'
                      sh "oc tag ${PROJECTNAME}/mysql:latest ${PROJECTNAME}/mysql:${DBVERSION}"
                    }
                  }
                }
              }
            }
            stage("Test application") {
              agent {label 'maven'}
              when {
                not { environment name: 'GITREPOTEST', value: 'false' }
              }
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/${BRANCHTEST}"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'tests']
                                ],
                                userRemoteConfigs: [[url: "${GITREPOTEST}"]]
                            ])
                  }
                }
                stage("Test environment") {
                  steps {
                    dir('tests') {
                      sh 'echo "You should perform tests to make sure your application works"'
                      sh 'echo "Something like a curl to a status port -  curl http://trades.dev2.conygre.com/trades/status"'
                      sh 'echo "Or http://trades.dev2.conygre.com/trades/list"'
                    }
                  }
                }
              }
            }
          }
        }
    type: JenkinsPipeline
    triggers: {}
