apiVersion: v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/display-name: frontend Image Stream
      description: >-
        frontend server Image Stream.
    from:
      kind: DockerImage
      name: dockerreg.conygre.com:5000/${PROJECTNAME}/frontend:${FRONTENDVERSION}
    generation: null
    importPolicy:
      insecure: true
    name: frontend:${FRONTENDVERSION}
status:
  dockerImageRepository: ""
