apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    io.kompose.service: mysql
  strategy:
    resources: {}
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
        openshift.io/scc: privileged
    spec:
      containers:
      - args:
        - --explicit_defaults_for_timestamp
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ${MYSQLROOTPW}
        image: ${DOCKERREG}/${PROJECTNAME}/mysql:${DBVERSION}
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: ${DBMOUNT}
          name: mysql-claim0
      restartPolicy: Always
      volumes:
      - name: mysql-claim0
        persistentVolumeClaim:
          claimName: mysql-claim0
  test: false
  triggers:
  - type: ConfigChange
status: {}
