apiVersion: v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/display-name: MySQL Image Stream
      description: >-
        MySQL server Image Stream.
    from:
      kind: DockerImage
      name: ${DOCKERREG}/${PROJECTNAME}/mysql:${DBVERSION}
    generation: null
    importPolicy:
      insecure: true
    name: mysql:${DBVERSION}
status:
  dockerImageRepository: ""
