apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: CONTAINERNAME
  annotations:
    openshift.io/image.insecureRepository: true
  name: CONTAINERNAME
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/display-name: CONTAINERNAME-image
      description: >-
        Image to launch CONTAINERNAME
    from:
      kind: DockerImage
      name: IMAGESTREAM
    generation: null
    importPolicy:
      insecure: true
    name: DOCKERIMAGETAG
status:
  dockerImageRepository: ""
